name: Deploy
on:
  push:
    branches: [master]
jobs:
  prune-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '0 minutes'
        skip-recent: 2 # KEEP PREVIOUS FOR ROLLBACK
  build-docker:
    runs-on: ubuntu-latest
    needs: prune-artifacts
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - run: docker build --tag ${{ github.event.repository.name }} .
    - run: docker save -o ${{ github.sha }}.tar ${{ github.event.repository.name }}
    - uses: actions/upload-artifact@v2
      with:
        name: build-docker@${{ github.sha }}
        path: ${{ github.sha }}.tar
  deploy-ansibile:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - uses: actions/download-artifact@v2
      with:
        name: build-docker@${{ github.sha }}
    - env:
        ANSIBLE_HOST_KEY_CHECKING: False
        ANSIBLE_SSH_COMMON_ARGS: '-o PreferredAuthentications=password'
      run: ansible-playbook --inventory ${{ github.event.repository.name }}, deploy.yml --extra-vars="ansible_user=${{ secrets.ansible_user }} ansible_password=${{ secrets.ansible_password }} github_sha=${{ github.sha }} github_repository_name=${{ github.event.repository.name }} slack_token=${{ secrets.slack_token }} slack_secret=${{ secrets.slack_secret }} openai_secret=${{ secrets.openai_secret }}"
